export const PRODUCT_LIST = "product_list"
export const PRODUCT_CREATE = "product_create"
export const PRODUCT_READ = "product_read"
export const PRODUCT_UPDATE = "product_update"
export const PRODUCT_DELETE = "product_delete"

export const CATEGORY_LIST = "category_list"
export const CATEGORY_CREATE = "category_create"
export const CATEGORY_READ = "category_read"
export const CATEGORY_UPDATE = "category_update"
export const CATEGORY_DELETE = "category_delete"

export const ORDER_LIST = "order_list"
export const ORDER_CREATE = "order_create"
export const ORDER_READ = "order_read"
export const ORDER_UPDATE = "order_update"
export const ORDER_DELETE = "order_delete"
export const ORDER_CANCEL = "order_cancel"

export const COMMENT_LIST = "comment_list"
export const COMMENT_CREATE = "comment_create"
export const COMMENT_READ = "comment_read"
export const COMMENT_UPDATE = "comment_update"
export const COMMENT_DELETE = "comment_delete"